<Project>
  <PropertyGroup>
    <BaseOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Personas\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Personas\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
